### PR TITLE
Label the edit product fields.

### PR DESCRIPTION
**Pull request by jwq1**
Label the text fields with instructive text for the user.

Re-organize the conditionals to remove repeative lines of code.

### CODE REVIEW

**Review by hdavidzhu — APPROVED** [review]

**Review by hdavidzhu — COMMENTED** [review]
With all this Javascript HTML element building, have you ever explored HTML templating engines like Handlebars?

http://handlebarsjs.com/

You can define HTML templates with some basic logic to help you navigate switching modes client-side.

**Comment by jwq1** [comment]
@hdavidzhu I already have the Jinja Templating Engine set up, but I am not sure how I would render multiple templates on the same URL path like we talked about earlier. 

Usually, I call `Flask.render_template` to render the specific file I want. The reason it is done with Flask+python, rather than Javascript+Handlebars, is because Jinja is a python templating language. I cannot call Jinja features from Javascript like I would with Handlebars. 

Typically the way I call python functions from Javascript is with a `GET` request. I construct the appropriate URL with Flask's `url_for` method, then get back the related python return value (e.g. `Flask.url_for(render-product-page, id=3)` invokes the python function which returns `render_template('product.html')` and changes the URL path to `'/product'`.

Up until now, if I render a template, I also change the URL path. Maybe I could try a few of the following options.

1. See if Flask allows multiple duplicate `@app.route()`.
2. Or write multiple functions within the same Flask `@app.route` then only call those functions based on conditionals. Conditionals would be based on a specific `GET` or `POST` request (e.g. I could use `Flask.url_for(render-product-page, function='edit')` which keeps the same `@app.route`, but uses a conditional to decide which page to render.

Something like the following.

```
@app.route('/product')
def function render-product-page():
    if (request.args.get('function') == 'edit')
        return render_template('edit.html')
    else if (request.args.get('function') == 'view')
        return render_template('product.html')
```

I am not sure if this is best practice, but I'll check around for better ideas. 

What do you think? Sound logical or is there a more typical way to accomplish this?

**Comment by hdavidzhu** [comment]
This is because your template is rendered/populated server-side, making this either really hard or impossible to accomplish.

Ideally, there may be a way to take the Jinja templates and populate them client-side. This would resolve your pains.

**Comment by jwq1** [comment]
@hdavidzhu  This is definitely something to do. It will make the code easier to collaborate on later. However, I moved it to "later optimization" rather than an MVP task.

Thank you for taking the time to suggest it. It's a worthwhile suggestion. I plan to do it asap.

**Pull request merged**
